title = "Marius Klocke"
baseURL = "http://localhost:8080"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "Paderborn, Germany"
email = "marius.klocke@gmail.com"
favicon = "/favicon.ico"
firstName = "Marius"
lastName = "Klocke"
profileImage = "img/profile.jpg"
showQr = true
showContact = false
showBoards = false
showCertifications = true
showSocializations = true
sections = ["skills", "creations", "contributions", "experience", "education"]

[[params.handles]]
name = "Xing"
link = "https://www.xing.com/profile/Marius_Klocke"

[[params.handles]]
name = "GitHub"
link = "https://github.com/mariusklocke"
icon = "github"

[[params.handles]]
name = "Docker Hub"
link = "https://hub.docker.com/u/mklocke"
icon = "docker"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"

