name: Build & Deploy Pages
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
        with:
          submodules: true
      - name: Build pages
        run: make build
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: public
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy pages from artifact
        uses: actions/deploy-pages@v4
